apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  annotations:
      openfunction.io/revision-controller: enable
      openfunction.io/revision-controller-params: |
        type: source
        repo-type: github
        polling-interval: 1m   
  name: function-http-java
spec:
  version: "v2.0.0"
  image: "programmermelayu/sample-java-func:v1"
  imageCredentials:
    name: push-secret
  port: 8080 # default to 8080
  build:
    builder: openfunction/builder-java:v2-18
    env:
      FUNC_NAME: "dev.openfunction.samples.HttpFunctionImpl"
      FUNC_CLEAR_SOURCE: "true"
    srcRepo:
      url: "https://github.com/programmermelayu/openfunction-samples.git"
      sourceSubPath: "functions/knative/java"
      revision: "main"
      credentials:
         name: git-repo-secret
  serving:
    template:
      containers:
        - name: function # DO NOT change this
          imagePullPolicy: IfNotPresent 
    runtime: "knative"
